### PR TITLE
Product Description, Process description log-3

### PR DESCRIPTION
**Pull request by jimena-garcia**

### CODE REVIEW

**Review by jeusmateo — CHANGES_REQUESTED** [review]
One scrum log is written in Spanish.

**Review by jimena-garcia — COMMENTED** [review]
Log-3 edit

**Review by jimena-garcia — COMMENTED** [review]
Log-3 edit

**Review by jeusmateo — APPROVED** [review]
Done

**Review by jimena-garcia — COMMENTED** [review]
Log-3

**Pull request merged**
